POST http://localhost:3000/api/users
Content-Type: application/json
Accept: application/json

{
  "username": "acroziqin",
  "password": "rahasia",
  "name": "Achmad Choirur Roziqin"
}

### f5540222-4098-4f45-a6ae-75341992c014

POST http://localhost:3000/api/users/login
Content-Type: application/json
Accept: application/json

{
  "username": "roziqin",
  "password": "rahasia"
}

###

GET http://localhost:3000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: 561a4dfa-dd6b-4ae6-a684-d415bfd23ce8

###

PATCH http://localhost:3000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: 561a4dfa-dd6b-4ae6-a684-d415bfd23ce8

{
  "name": "Ceisya Kinaraisha"
}

###

DELETE http://localhost:3000/api/users/logout
Content-Type: application/json
Accept: application/json
Authorization: 561a4dfa-dd6b-4ae6-a684-d415bfd23ce8

###

POST http://localhost:3000/api/contacts
Content-Type: application/json
Accept: application/json
Authorization: 561a4dfa-dd6b-4ae6-a684-d415bfd23ce8

{
  "first_name": "Joko",
  "last_name": "Morro",
  "email": "joko@pzn.com",
  "phone": "123443124321"
}

###

GET http://localhost:3000/api/contacts
Content-Type: application/json
Accept: application/json
Authorization: 561a4dfa-dd6b-4ae6-a684-d415bfd23ce8

###

GET http://localhost:3000/api/contacts/10
Content-Type: application/json
Accept: application/json
Authorization: 561a4dfa-dd6b-4ae6-a684-d415bfd23ce8

###

GET http://localhost:3000/api/contacts?name=belas&page=2
Content-Type: application/json
Accept: application/json
Authorization: 561a4dfa-dd6b-4ae6-a684-d415bfd23ce8

###

PUT http://localhost:3000/api/contacts/501
Content-Type: application/json
Accept: application/json
Authorization: 561a4dfa-dd6b-4ae6-a684-d415bfd23ce8

{
  "first_name": "Rully",
  "last_name": "Nugraha",
  "email": "rully@pzn.com",
  "phone": "123443124321"
}

###

DELETE http://localhost:3000/api/contacts/501
Content-Type: application/json
Accept: application/json
Authorization: 561a4dfa-dd6b-4ae6-a684-d415bfd23ce8

### Create Address

POST http://localhost:3000/api/contacts/500/addresses
Content-Type: application/json
Accept: application/json
Authorization: 561a4dfa-dd6b-4ae6-a684-d415bfd23ce8

{
  "street": "Kantor",
  "city": "Jakarta",
  "province": "DKI JAKARTA",
  "country": "Indonesia",
  "postal_code": "324324"
}

###

GET http://localhost:3000/api/contacts/500/addresses
Content-Type: application/json
Accept: application/json
Authorization: 561a4dfa-dd6b-4ae6-a684-d415bfd23ce8

###

GET http://localhost:3000/api/contacts/500/addresses/58
Content-Type: application/json
Accept: application/json
Authorization: 561a4dfa-dd6b-4ae6-a684-d415bfd23ce8

### Update Address

PUT http://localhost:3000/api/contacts/500/addresses/58
Content-Type: application/json
Accept: application/json
Authorization: 561a4dfa-dd6b-4ae6-a684-d415bfd23ce8

{
  "street": "Kantor Bekerja",
  "city": "Surabaya",
  "province": "Jawa Timur",
  "country": "Indonesia",
  "postal_code": "324324"
}

### Remove Address

DELETE http://localhost:3000/api/contacts/500/addresses/58
Content-Type: application/json
Accept: application/json
Authorization: 561a4dfa-dd6b-4ae6-a684-d415bfd23ce8